### ISSUE TITLE
Хто за які пункти відповідає?

### ISSUE THREAD

**Issue by RKDGT** [Yura09/command-work#2]

**Comment by RKDGT** [comment]
1)Місце подорожі
2)Ночівля
3)Харчування (заклади громадського харчування, самостійне приготування):
4)Медичне забезпечення
5)Засоби комунікації між мандрівниками і з рідними, що залишилися вдома
6)Засоби фото і відео реєстрації, можливо, ведення онлайн трансляції
7)Дозволи від місцевої влади чи спеціальних служб, якщо обрано особливе місце (прикордонна зона, високогір’я, сплав річкою тощо)

8)Кошторис подорожі, розрахований загалом та на кожного

**Comment by KrisstinaL** [comment]
Я можу взяти 1 і 4

**Comment by Yura09** [comment]
2 і 5
