### ISSUE TITLE
Місце подорожі

### ISSUE THREAD

**Issue by Yura09** [Yura09/command-work#3]
Потрібно визначитись в яке місто їдемо)) 
а) Назва, відстань , маршрут, вид транспорту, час на добирання.
б) Чим цікаве вибране місце, його історія, пам'ятки, легенди, герої тощо. Які тут є розваги чи корисні заняття.

**Comment by KrisstinaL** [comment]
Я пропоную поїхати кудись, де красива природа..Можливо десь біля лісу

**Comment by KrisstinaL** [comment]
Можливо десь на Закарпаття?

**Comment by RKDGT** [comment]
Пропоную Мюнхен(Октоберфест)

**Comment by Yura09** [comment]
Чудова ідея, можна десь біля Синевиру

**Comment by RKDGT** [comment]
ок... гори, так гори )

**Comment by KrisstinaL** [comment]
Але біля Синевиру немає дуже розваг, як от наприклад в Буковелі)

**Comment by RKDGT** [comment]
ну давай)

**Comment by Yura09** [comment]
Я не проти, давайте тоді в Буковель)

**Comment by Yura09** [comment]
Пропоную Христі дізнатись більше про Буковель, і як нам добратись туди

**Comment by KrisstinaL** [comment]
Гаразд, я зберу всьо інформацію та поділюсь з вами)
