### ISSUE TITLE
Харчування

### ISSUE THREAD

**Issue by RKDGT** [Yura09/command-work#5]
Ваші бажання на рахунок того, де/як б ви хотіли харчуватись(готуємо самі, чи відвідуєм заклади харчування)?
а) в дорозі
б) на місці

**Comment by RKDGT** [comment]
відповідно до ваших бажань я підготую інформацію нарахунок закладів, або того що ми можемо пригот для себе))
якось так)

**Comment by KrisstinaL** [comment]
Думаю, що якщо ми завжди будемо харчуватись в закладах, то це вийде нам досить таки дорого. Звичайно як будемо в дорозі, потрібно буде кожному взяти з собою якусь їжу, а на місці, то можна по різному

**Comment by KrisstinaL** [comment]
@Yura09  а ти як вважаєш?

**Comment by RKDGT** [comment]
Я погоджуюсь з цим, але тоді як краще на вашу думку організувати харчування в дорозі, а також я підготую список закладів які ми зможемо відвідати вже на місці
ок?

**Comment by Yura09** [comment]
@RKDGT окей)

**Comment by RKDGT** [comment]
але тоді як краще на вашу думку організувати харчування в дорозі?
